# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-25 16:47
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('vcard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='tech_name',
            field=models.CharField(default='this-field-intended-to-be-unique', help_text='Only latin letters, digits, underscores, hyphens.', max_length=255, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z', 32), "Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens.", 'invalid')]),
            preserve_default=False,
        ),
    ]
