# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 14:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('vcard', '0004_auto_20151226_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', easy_thumbnails.fields.ThumbnailerImageField(upload_to='projects')),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='picture',
        ),
        migrations.AddField(
            model_name='projectpicture',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vcard.Project'),
        ),
    ]
