# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 16:26
from __future__ import unicode_literals

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('vcard', '0005_auto_20160104_1430'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectPicture',
            new_name='ProjectAdditionalPicture',
        ),
        migrations.AddField(
            model_name='project',
            name='main_picture',
            field=easy_thumbnails.fields.ThumbnailerImageField(default='fdfd', upload_to='projects'),
            preserve_default=False,
        ),
    ]
